<a href="https://colab.research.google.com/github/PLucenaa/PLucenaa/blob/main/VERS%C3%83O_OFICIAL_Intera%C3%A7%C3%A3o_de_Medicamentos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1 - Instalando Bibliotecas**

In [ ]:
!pip install -q -U google-generativeai

In [ ]:
!pip install gradio

Collecting gradio
  Downloading gradio-5.9.1-py3-none-any.whl.metadata (16 kB)
Collecting aiofiles<24.0,>=22.0 (from gradio)
  Downloading aiofiles-23.2.1-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (3.7.1)
Collecting fastapi<1.0,>=0.115.2 (from gradio)
  Downloading fastapi-0.115.6-py3-none-any.whl.metadata (27 kB)
Collecting ffmpy (from gradio)
  Downloading ffmpy-0.4.0-py3-none-any.whl.metadata (2.9 kB)
Collecting gradio-client==1.5.2 (from gradio)
  Downloading gradio_client-1.5.2-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: httpx>=0.24.1 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub>=0.25.1 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.27.0)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (3.1.4)
Collecting markupsafe~=2.0 (from gradio)
  Downloading MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (1.26.4)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (3.10.12)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from gradio) (24.2)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (11.0.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (2.10.3)
Collecting pydub (from gradio)
  Downloading pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting python-multipart>=0.0.18 (from gradio)
  Downloading python_multipart-0.0.20-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (6.0.2)
Collecting ruff>=0.2.2 (from gradio)
  Downloading ruff-0.8.3-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (25 kB)
Collecting safehttpx<0.2.0,>=0.1.6 (from gradio)
  Downloading safehttpx-0.1.6-py3-none-any.whl.metadata (4.2 kB)
Collecting semantic-version~=2.0 (from gradio)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting starlette<1.0,>=0.40.0 (from gradio)
  Downloading starlette-0.42.0-py3-none-any.whl.metadata (6.0 kB)
Collecting tomlkit<0.14.0,>=0.12.0 (from gradio)
  Downloading tomlkit-0.13.2-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.15.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (4.12.2)
Collecting uvicorn>=0.14.0 (from gradio)
  Downloading uvicorn-0.34.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from gradio-client==1.5.2->gradio) (2024.10.0)
Requirement already satisfied: websockets<15.0,>=10.0 in /usr/local/lib/python3.10/dist-packages (from gradio-client==1.5.2->gradio) (14.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5.0,>=3.0->gradio) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio<5.0,>=3.0->gradio) (1.3.1)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5.0,>=3.0->gradio) (1.2.2)
Collecting starlette<1.0,>=0.40.0 (from gradio)
  Downloading starlette-0.41.3-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx>=0.24.1->gradio) (2024.12.14)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx>=0.24.1->gradio) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx>=0.24.1->gradio) (0.14.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.1->gradio) (3.16.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.1->gradio) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.1->gradio) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio) (2024.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.1 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2.0->gradio) (2.27.1)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0,>=0.12->gradio) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.18.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.25.1->gradio) (3.4.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.25.1->gradio) (2.2.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)
Downloading gradio-5.9.1-py3-none-any.whl (57.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.2/57.2 MB 10.5 MB/s eta 0:00:00
Downloading gradio_client-1.5.2-py3-none-any.whl (320 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.4/320.4 kB 22.4 MB/s eta 0:00:00
Downloading aiofiles-23.2.1-py3-none-any.whl (15 kB)
Downloading fastapi-0.115.6-py3-none-any.whl (94 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.8/94.8 kB 6.3 MB/s eta 0:00:00
Downloading MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Downloading python_multipart-0.0.20-py3-none-any.whl (24 kB)
Downloading ruff-0.8.3-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 73.9 MB/s eta 0:00:00
Downloading safehttpx-0.1.6-py3-none-any.whl (8.7 kB)
Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Downloading starlette-0.41.3-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.2/73.2 kB 5.9 MB/s eta 0:00:00
Downloading tomlkit-0.13.2-py3-none-any.whl (37 kB)
Downloading uvicorn-0.34.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 4.7 MB/s eta 0:00:00
Downloading ffmpy-0.4.0-py3-none-any.whl (5.8 kB)
Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Installing collected packages: pydub, uvicorn, tomlkit, semantic-version, ruff, python-multipart, markupsafe, ffmpy, aiofiles, starlette, safehttpx, gradio-client, fastapi, gradio
  Attempting uninstall: markupsafe
    Found existing installation: MarkupSafe 3.0.2
    Uninstalling MarkupSafe-3.0.2:
      Successfully uninstalled MarkupSafe-3.0.2
Successfully installed aiofiles-23.2.1 fastapi-0.115.6 ffmpy-0.4.0 gradio-5.9.1 gradio-client-1.5.2 markupsafe-2.1.5 pydub-0.25.1 python-multipart-0.0.20 ruff-0.8.3 safehttpx-0.1.6 semantic-version-2.10.0 starlette-0.41.3 tomlkit-0.13.2 uvicorn-0.34.0

In [ ]:
import google.generativeai as genai
import gradio as gr
import textwrap
import numpy as np
import pandas as pd
import re
import unicodedata
import nltk

In [ ]:
from google.colab import userdata
GOOGLE_API_KEY=userdata.get('GOOGLE_API_KEY')
genai.configure(api_key=GOOGLE_API_KEY)

In [ ]:
for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
    print(m.name)

models/gemini-1.0-pro-latest
models/gemini-1.0-pro
models/gemini-pro
models/gemini-1.0-pro-001
models/gemini-1.0-pro-vision-latest
models/gemini-pro-vision
models/gemini-1.5-pro-latest
models/gemini-1.5-pro-001
models/gemini-1.5-pro-002
models/gemini-1.5-pro
models/gemini-1.5-pro-exp-0801
models/gemini-1.5-pro-exp-0827
models/gemini-1.5-flash-latest
models/gemini-1.5-flash-001
models/gemini-1.5-flash-001-tuning
models/gemini-1.5-flash
models/gemini-1.5-flash-exp-0827
models/gemini-1.5-flash-002
models/gemini-1.5-flash-8b
models/gemini-1.5-flash-8b-001
models/gemini-1.5-flash-8b-latest
models/gemini-1.5-flash-8b-exp-0827
models/gemini-1.5-flash-8b-exp-0924
models/gemini-2.0-flash-exp
models/gemini-exp-1206
models/gemini-exp-1121
models/gemini-exp-1114
models/learnlm-1.5-pro-experimental

In [ ]:
model = genai.GenerativeModel('gemini-1.5-flash-latest')

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem.snowball import SnowballStemmer
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# **2 - Montando o Drive no Google Colab e Carregando o DataSet**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/IA na Saúde/Hands-On/Base de Dados/interacao_300.xlsx')
df.head()

,Droga A,Droga B,Mecanismos de Interação
0,Abacavir,Acetato de sódio,O abacavir pode diminuir a taxa de excreção de...
1,Acetazolamida,Acetato de sódio,A acetazolamida pode aumentar a taxa de excreç...
2,Aciclovir,Acetato de sódio,O aciclovir pode diminuir a taxa de excreção d...
3,Ácido acetilsalicílico,Acetato de sódio,O ácido acetilsalicílico pode diminuir a taxa ...
4,Alopurinol,Acetato de sódio,O alopurinol pode diminuir a taxa de excreção ...

# **3 - Tratamento dos Dados**

In [ ]:
def tratar_texto(texto):
    texto = texto.lower()

    texto = unicodedata.normalize('NFD', texto)
    texto = ''.join([c for c in texto if unicodedata.category(c) != 'Mn'])

    texto = re.sub(r'[^\w\s]', ' ', texto)
    texto = re.sub(r'\d+', 'NUM', texto)
    tokens = word_tokenize(texto, language='portuguese')

    stop_words = set(stopwords.words('portuguese'))
    tokens = [word for word in tokens if word not in stop_words]

    stemmer = SnowballStemmer("portuguese")
    tokens = [stemmer.stem(word) for word in tokens]

    texto_preprocessado = ' '.join(tokens)
    return texto_preprocessado

In [ ]:
df['Mecanismos de Interação Tratados'] = df['Mecanismos de Interação'].apply(tratar_texto)
df.head()

,Droga A,Droga B,Mecanismos de Interação,Mecanismos de Interação Tratados
0,Abacavir,Acetato de sódio,O abacavir pode diminuir a taxa de excreção de...,abacav pod diminu tax excreca acetat sodi pod ...
1,Acetazolamida,Acetato de sódio,A acetazolamida pode aumentar a taxa de excreç...,acetazolam pod aument tax excreca acetat sodi ...
2,Aciclovir,Acetato de sódio,O aciclovir pode diminuir a taxa de excreção d...,aciclov pod diminu tax excreca acetat sodi pod...
3,Ácido acetilsalicílico,Acetato de sódio,O ácido acetilsalicílico pode diminuir a taxa ...,acid acetilsalicil pod diminu tax excreca acet...
4,Alopurinol,Acetato de sódio,O alopurinol pode diminuir a taxa de excreção ...,alopurinol pod diminu tax excreca acetat sodi ...

# **4 - Análise de Gravidade**

In [ ]:
def classificar_gravidade(texto):
    texto = texto.lower()
    if re.search(r'(aumenta|aumentar as atividades|risco ou gravidade|perda de eficácia)', texto):
        return "Grave"
    elif re.search(r'(diminui|diminuir|reduz|minimiza)', texto):
        return "Leve"
    elif re.search(r'(pode aumentar|pode diminuir|pode ser aumentado|pode ser diminuído|pode ser aumentada|pode ser diminuída)', texto):
        return "Moderada"

In [ ]:
df['Classificação de Gravidade'] = df['Mecanismos de Interação'].apply(classificar_gravidade)
df.head()

,Droga A,Droga B,Mecanismos de Interação,Mecanismos de Interação Tratados,Classificação de Gravidade
0,Abacavir,Acetato de sódio,O abacavir pode diminuir a taxa de excreção de...,abacav pod diminu tax excreca acetat sodi pod ...,Leve
1,Acetazolamida,Acetato de sódio,A acetazolamida pode aumentar a taxa de excreç...,acetazolam pod aument tax excreca acetat sodi ...,Grave
2,Aciclovir,Acetato de sódio,O aciclovir pode diminuir a taxa de excreção d...,aciclov pod diminu tax excreca acetat sodi pod...,Leve
3,Ácido acetilsalicílico,Acetato de sódio,O ácido acetilsalicílico pode diminuir a taxa ...,acid acetilsalicil pod diminu tax excreca acet...,Leve
4,Alopurinol,Acetato de sódio,O alopurinol pode diminuir a taxa de excreção ...,alopurinol pod diminu tax excreca acetat sodi ...,Leve

In [ ]:
df['Classificação de Gravidade'].value_counts()

Classificação de Gravidade
Grave       191
Leve         86
Moderada     52
Name: count, dtype: int64

# **5 - Gerando Embeddings**

In [ ]:
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(df['Mecanismos de Interação Tratados'])
df['Embeddings'] = tfidf_matrix.toarray().tolist()
df.head()

,Droga A,Droga B,Mecanismos de Interação,Mecanismos de Interação Tratados,Classificação de Gravidade,Embeddings
0,Abacavir,Acetato de sódio,O abacavir pode diminuir a taxa de excreção de...,abacav pod diminu tax excreca acetat sodi pod ...,Leve,"[0.43778916206971336, 0.0, 0.0, 0.0, 0.3931278..."
1,Acetazolamida,Acetato de sódio,A acetazolamida pode aumentar a taxa de excreç...,acetazolam pod aument tax excreca acetat sodi ...,Grave,"[0.0, 0.0, 0.0, 0.0, 0.3309887007320972, 0.296..."
2,Aciclovir,Acetato de sódio,O aciclovir pode diminuir a taxa de excreção d...,aciclov pod diminu tax excreca acetat sodi pod...,Leve,"[0.0, 0.0, 0.0, 0.0, 0.40063184337280633, 0.0,..."
3,Ácido acetilsalicílico,Acetato de sódio,O ácido acetilsalicílico pode diminuir a taxa ...,acid acetilsalicil pod diminu tax excreca acet...,Leve,"[0.0, 0.0, 0.0, 0.0, 0.38982824212512834, 0.0,..."
4,Alopurinol,Acetato de sódio,O alopurinol pode diminuir a taxa de excreção ...,alopurinol pod diminu tax excreca acetat sodi ...,Leve,"[0.0, 0.0, 0.0, 0.0, 0.3869294626141523, 0.0, ..."

# **6 - Consultando Interações Medicamentosas**

In [ ]:
def buscar_interacao(pergunta):
    pergunta = tratar_texto(pergunta)
    embedding_pergunta = vectorizer.transform([pergunta]).toarray()
    similaridades = cosine_similarity(embedding_pergunta, np.vstack(df['Embeddings']))
    idx_max_similaridade = np.argmax(similaridades)
    resultado = df.iloc[idx_max_similaridade]
    gravidade = resultado['Classificação de Gravidade']
    mecanismo_interacao = resultado['Mecanismos de Interação']

    prompt = (
            f"Considere o seguinte mecanismo de interação medicamentosa: '{mecanismo_interacao}' e a gravidade classificada como '{gravidade}'. "
            f"Crie uma recomendação clara, pequena e breve para o médico sobre o que fazer."
            f"No final do texto, sugira dois medicamentos alternativos que são mais prescritos no Brasil, que possam ser utilizados com segurança e diga para o que eles são indicados.")
    resposta = model.generate_content(prompt)

    if resposta:
        return f"Interação\n{resultado['Mecanismos de Interação']}\n\n"\
               f"Gravidade da Interação\n{resultado['Classificação de Gravidade']}.\n\n"\
               f"Recomendações\n{resposta.text}"
    else:
        return "Nenhuma interação medicamentosa entre os medicamentos. No entanto, não significa que não haja interação."

In [ ]:
def formatar_texto(texto):
    texto = re.sub(r'[^\w\s.,]', '', texto)
    texto = re.sub(r'^\*', '', texto)
    texto = re.sub(r'\. +', '.\n', texto)
    return texto

In [ ]:
pergunta = "Posso prescrever dipirona com paracetamol?"
resultado = buscar_interacao(pergunta)
resultado = formatar_texto(resultado)
print(resultado)

Interação
A dipirona pode diminuir a taxa de excreção de paracetamol, o que pode resultar em um nível sérico mais alto.

Gravidade da Interação
Leve.

Recomendações
Monitorar cuidadosamente os níveis séricos de paracetamol em pacientes que utilizam concomitantemente dipirona.
Considerar redução da dose de paracetamol ou uso alternativo caso necessário.

Alternativas  ibuprofeno antiinflamatório, analgésico, antipirético e naproxeno antiinflamatório, analgésico.

# **7 - Interface com Gradio**

In [ ]:
def gradio_buscar_interacao(pergunta):
    try:
        resposta = buscar_interacao(pergunta)
        resposta = formatar_texto(resposta)
        return resposta
    except Exception as e:
        return f"Erro ao buscar interação: {str(e)}"

iface = gr.Interface(
    fn=buscar_interacao,
    inputs=gr.Textbox(label="Pergunta sobre Interação Medicamentosa", placeholder="Digite sua pergunta aqui...", lines=3),
    outputs=gr.Textbox(label="Resposta", lines=3),
    title="VerificaMed",
    description="Digite uma pergunta sobre interação medicamentosa para obter informações.")
iface.launch(debug=True)

Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://16b72e38ba3068e22e.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)